
# Server Port \uC785\uB825\uD558\uAE30
server:
  port: 8080
# \uC2A4\uD504\uB9C1 \uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uC774\uB984 \uC9C0\uC815
#  servlet:
#    context-path: /test
spring:
  application:
    name: spring-study
  # PostgreSQL \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC5F0\uACB0 \uC815\uBCF4
  datasource:
      url: jdbc:postgresql://localhost:5432/study
      username: study
      password: qweasdzxc12!
      driver-class-name: org.postgresql.Driver
    # JPA \uC124\uC815
  jpa:
      show-sql: true # SQL \uCFFC\uB9AC \uBCF4\uC774\uAE30 (\uAC1C\uBC1C \uD658\uACBD\uC5D0\uC11C \uC720\uC6A9)
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate:
        # NONE\uC73C\uB85C \uD558\uB294\uAC8C \uBCA0\uC2A4\uD2B8\uACE0 \uC0AC\uC2E4\uC0C1 \uC544\uC608 \uC544\uBB34\uAC83\uB3C4 \uC124\uC815\uD558\uC9C0 \uC54A\uB294\uAC8C \uC88B\uB2E4.
        # \uC0C1\uC6A9\uC5D0\uC11C \uC774\uAC70 \uAC74\uB4E4\uBA74 \uC870\uC9C4\uB2E4. \uC9C4\uC9DC\uB85C
#        ddl-auto: update
# \uC2A4\uD504\uB9C1 \uBE48 \uC9C0\uC5F0 \uB85C\uB529\uC73C\uB85C \uB9CC\uB4E4\uAE30
#  main:
#    lazy-initialization: true

# Actuator \uC124\uC815
# \uD65C\uC131\uD654\uD560 End Point
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true # env \uD658\uACBD\uC124\uC815 \uC815\uBCF4 \uB178\uCD9C \uC5EC\uBD80

# Actuator App Info \uC0AC\uC6A9\uC790 \uC9C0\uC815 \uCD94\uAC00
info:
  app:
    name: My Study App
    description : \uB098\uB294 \uAC1C\uBC1C\uC790\uB2E4. \uADF8\uB9AC\uACE0 \uB0B4 \uC571\uC740 \uC0B4\uC544 \uC228\uC270\uB2E4.
    version: 1.0.0

my:
  name : Cononi
  age : 28
