
# Server Port 입력하기
server:
  port: 8080
# 스프링 애플리케이션 이름 지정
#  servlet:
#    context-path: /test
spring:
  application:
    name: spring-study
  # PostgreSQL 데이터베이스 연결 정보
  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: study
    password: qweasdzxc12!
    driver-class-name: org.postgresql.Driver
    # JPA 설정
  jpa:
    show-sql: true # SQL 쿼리 보이기 (개발 환경에서 유용)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # NONE으로 하는게 베스트고 사실상 아예 아무것도 설정하지 않는게 좋다.
      # 상용에서 이거 건들면 조진다. 진짜로
      ddl-auto: create

# Actuator 설정
# 활성화할 End Point
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true # env 환경설정 정보 노출 여부

my:
  name : Cononi
  age : 28
